// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrbitPM.Data;

#nullable disable

namespace OrbitPM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260413003038_CustomAuthMigration")]
    partial class CustomAuthMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrbitPM.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OrbitPM.Models.MatchRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MatchedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectProposalId")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectProposalId")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("MatchRecords");
                });

            modelBuilder.Entity("OrbitPM.Models.ProjectProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResearchAreaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalStack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResearchAreaId");

                    b.ToTable("ProjectProposals");
                });

            modelBuilder.Entity("OrbitPM.Models.ProposalOwnership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectProposalId")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectProposalId")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.ToTable("ProposalOwnerships");
                });

            modelBuilder.Entity("OrbitPM.Models.ResearchArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResearchAreas");
                });

            modelBuilder.Entity("OrbitPM.Models.SupervisorResearchArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ResearchAreaId")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ResearchAreaId");

                    b.HasIndex("SupervisorId", "ResearchAreaId")
                        .IsUnique();

                    b.ToTable("SupervisorResearchAreas");
                });

            modelBuilder.Entity("OrbitPM.Models.MatchRecord", b =>
                {
                    b.HasOne("OrbitPM.Models.ProjectProposal", "ProjectProposal")
                        .WithOne("MatchRecord")
                        .HasForeignKey("OrbitPM.Models.MatchRecord", "ProjectProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrbitPM.Models.ApplicationUser", "Supervisor")
                        .WithMany("Matches")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectProposal");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("OrbitPM.Models.ProjectProposal", b =>
                {
                    b.HasOne("OrbitPM.Models.ResearchArea", "ResearchArea")
                        .WithMany("Proposals")
                        .HasForeignKey("ResearchAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchArea");
                });

            modelBuilder.Entity("OrbitPM.Models.ProposalOwnership", b =>
                {
                    b.HasOne("OrbitPM.Models.ProjectProposal", "ProjectProposal")
                        .WithOne("Ownership")
                        .HasForeignKey("OrbitPM.Models.ProposalOwnership", "ProjectProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrbitPM.Models.ApplicationUser", "Student")
                        .WithMany("ProposalOwnerships")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectProposal");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OrbitPM.Models.SupervisorResearchArea", b =>
                {
                    b.HasOne("OrbitPM.Models.ResearchArea", "ResearchArea")
                        .WithMany("SupervisorResearchAreas")
                        .HasForeignKey("ResearchAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrbitPM.Models.ApplicationUser", "Supervisor")
                        .WithMany("SupervisorResearchAreas")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchArea");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("OrbitPM.Models.ApplicationUser", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("ProposalOwnerships");

                    b.Navigation("SupervisorResearchAreas");
                });

            modelBuilder.Entity("OrbitPM.Models.ProjectProposal", b =>
                {
                    b.Navigation("MatchRecord");

                    b.Navigation("Ownership");
                });

            modelBuilder.Entity("OrbitPM.Models.ResearchArea", b =>
                {
                    b.Navigation("Proposals");

                    b.Navigation("SupervisorResearchAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
